image: golang:1.15

stages:
  - test
  - build

unit_tests:
  stage: test
  script:
    - make test

lint_code:
  image: golangci/golangci-lint:v1.31
  stage: test
  script:
    - make lint

build:
  stage: build
  script:
    - make
