name: Trigger go.anx.io update

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trigger:
    name:    Trigger go.anx.io update
    runs-on: ubuntu-latest
    steps:
    - uses: anexia-it/go.anx.io@main
      env:
        GOANXIO_E5E_TOKEN: "${{ secrets.GOANXIO_E5E_TOKEN }}"
